### PR TITLE
#44 adding tutorial metadata

### LINKED ISSUE #44: YAML Frontmatter in tutorials
Because we convert tutorials to HTML with Jekyll (http://jekyllrb.com) it would be useful to include metadata at the top of each tutorial.

I plan on adding the following tags to the top of tutorials

| metadata tag | description | where utilized | 
|-----------|------------|------|
| `tutorial-version`| version tag for which current tutorial is compatible | inserted into html link to for button on tutorial footer |
|`tutorial-series` |series which tutorial is a part of | no current plans but I feel would be useful for organization in the future|
|`title` |pretty self explanatory here |no specific uses yet but alas something we can use to insert if we ever needed it. Also helpful to make an "official" title for some of the tutorials | 
| `tutorial-id` | This will be used to identify tutorial in hortonworks community connection | used when inserting data into links for tutorial footer|
| `intro-page` | true or false value | can be used to insert extra data in top/bottom of paragraph if needed - no current use |
| `components` | a string array of values which specifies the hdp/hdf components which are used in the tutorial. | no specific plans - but could be utilized on gh-pages? Definitely something that could be useful. |

The build script also needs to be modified to not add YAML frontmatter since all tutorials should already contain it after this fix.

@roberthryniewicz @james94 @racoss

### PR DESCRIPTION
**Pull request by ZacBlanco**
Resolves #44 - All tutorials should now contain YAML front matter and script should auto-insert id’s and such when building

### CODE REVIEW

**Comment by ZacBlanco** [comment]
@roberthryniewicz @james94 Can you guys both please copy this branch locally and do some testing with the tutorial builds. Make sure it all works good for your tutorials and that it's properly formatted.

If you want another feature or separate metadata tag that you think we should add please let me know now before I merge

Once I get the OK from you guys I'll do the merge. I just want your approval on it all first since it practically affects every tutorial

Thanks!

**Comment by ZacBlanco** [comment]
Previous commit resolved merge conflicts

**Comment by james94** [comment]
Hey Zac. Yeah I will do some testing today.

Thanks.

-James

**Comment by ZacBlanco** [comment]
All tutorials now updated with new HTML per #59 
Merging.

**Pull request merged**
