### PR TITLE
Fixed issues in Sentiment Analysis Tutorial

### LINKED ISSUE #8: Sentiment Analysis Tutorial Issues
Issues that are being resolved include

- Grammatical errors

- Compatibility for Azure Users
     1. downloading Apache NiFi
     2. ssh into Sandbox
     3. forwarding port with GUI
     4. analyzing tweet data in hive

- Commands not functioning property

- Ambari Interface, brief navigation to Zeppelin (just in case it doesn't appear in views)

### PR DESCRIPTION
**Pull request by james94**
Fixed #8, #6 of the issues.

### CODE REVIEW

**Comment by james94** [comment]
I had edited the commit comment that has title Fixed num7 to num8, but I don't think it changed since it's still the same as before.

**Comment by ZacBlanco** [comment]
James - in the intro there is a link you added for users to get setup on azure. It points to a tutorial which is on GitHub...I think we should use this instead: http://hortonworks.com/hadoop-tutorial/deploying-hortonworks-sandbox-on-microsoft-azure/

The link which you used is outdated.

**Comment by ZacBlanco** [comment]
@james94  I think if you can just fix that link I mentioned in the above comment we can merge the pull request.

**Comment by james94** [comment]
I will fix the link now.

**Pull request merged**
